version: '3.9'

services:

  backend:
    build: ./backend
    image: mchamsteryt2/drawprism-server-side
    container_name: server-side
    expose:
      - 8020
  
  front-end:
    build: ./front-end
    image: mchamsteryt2/drawprism-client-side
    container_name: client-side
    expose:
      - 80
    ports:
      - 2080:80
      - 2443:443
